image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install jekyll
  - gem install redcarpet
  - gem install jekyll-paginate
  - jekyll build -d site/
  artifacts:
    paths:
    - site
  only:
  - master
