image: ruby:2.3 

pages:
  stage: deploy
  script:
  - bundle install jekyll
  - bundle install redcarpet
  - bundle install jekyll-paginate
  - bundle install jekyll-sitemap
  - bundle install jekyll-seo-tag  
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
