markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
pygments: true
permalink: /:title
timezone: Brazil/Sao_Paulo
encoding: utf-8
