# Dependencies
markdown:         kramdown
#highlighter:      pygments
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink:        /:categories/:title/
#permalink:        pretty
#relative_permalinks: true
encoding: utf-8

# Setup
title:            Os Cacarecos do Fábio
tagline:          'Onde coloco tudo o que dá na telha'
description:      ''
url:              http://fabiocosta0305.github.io/
baseurl:          '/'

author:
  name:           'Fábio Emilio Costa'
  email:          fabiocosta0305@gmail.com
  twitter:        hufflepuffbr
  facebook:       fabiocosta0305
  googleplus:     +FabioEmilioCosta
  linkedin:       fabiocosta0305
  instagram:      hufflepuffbr
  telegram:       hufflepuffbr 
  youtube:        fabiocosta0305
  avatar:         /images/meuAvatar2015-orig.png


paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  tipos:
    output: true
  rpg-a-day:
    output: true

#excerpt_separator: "\n---\n"
excerpt_separator: <!-- excerpt -->
